=== educelab/ink-id/inkid/schemas/dataSource0.1.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://cs.uky.edu/educe/schemas/dataSource0.1.schema.json",
  "title": "Data Source",
  "description": "A data source for use with ink-id",
  "type": "object",
  "properties": {
    "schema_version": {
      "description": "The version of the dataSource schema this file was made to fulfill",
      "const": "0.1"
    },
    "type": {
      "description": "The kind of data source (region or volume)",
      "enum": ["region", "volume"]
    },
    "volume": {
      "description": "Volume path relative to this data source file",
      "type": "string"
    },
    "ppm": {
      "description": "PPM path relative to this data source file",
      "type": "string"
    },
    "mask": {
      "description": "PPM mask image path relative to this data source file",
      "type": ["string", "null"]
    },
    "invert_normals": {
      "description": "Whether to invert the normals from this region before sampling subvolumes",
      "type": "boolean"
    },
    "bounding_box": {
      "description": "bounding box array [left, top, right, bottom], or null (indicating region occupies entire PPM bounds)",
      "type": ["array", "null"],
      "minItems": 4,
      "maxItems": 4,
      "items": {
        "type": "number"
      }
    },
    "volume_bounding_box": {
      "description": "bounding box array [min_x, min_y, min_z, max_x, max_y, max_z], or null (indicating volume occupies entire volume bounds). only applicable for volume data sources.",
      "type": ["array", "null"],
      "minItems": 6,
      "maxItems": 6,
      "items": {
          "type": "number"
      }
    },
    "ink_label": {
      "description": "Ink label image path relative to this data source file",
      "type": ["string", "null"]
    },
    "rgb_label": {
      "description": "RGB label image path relative to this data source file",
      "type": ["string", "null"]
    },
    "volcart_texture_label": {
      "description": "Volume Cartographer texture label image path relative to this data source file",
      "type": ["string", "null"]
    }
  },
  "required": [ "schema_version", "type", "volume" ],
  "if": {
    "properties": { "type": { "const": "region" } }
  },
  "then": {
    "required": ["ppm", "mask", "invert_normals", "bounding_box", "ink_label", "rgb_label", "volcart_texture_label"]
  }
}

=== educelab/ink-id/inkid/examples/DummyTest.volpkg/working/DummyTestMultiChannelInkLabel.json
{
  "schema_version": "0.1",
  "type": "region",
  "volume": "../volumes/20200526145449",
  "ppm": "../paths/20200526152035/textSurface.ppm",
  "mask": "../paths/20200526152035/textSurface_mask.png",
  "invert_normals": false,
  "bounding_box": null,
  "ink_label": "../paths/20200526152035/textSurface_ink-mask_rgb-image-mode.png",
  "rgb_label": "../paths/20200526152035/textSurface_rgb-mask.png",
  "volcart_texture_label": null
}

=== educelab/ink-id/inkid/examples/DummyTest.volpkg/working/DummyTest.json
{
  "schema_version": "0.1",
  "type": "region",
  "volume": "../volumes/20200526145449.zarr256",
  "ppm": "../paths/20200526152035/textSurface.ppm",
  "mask": "../paths/20200526152035/textSurface_mask.png",
  "invert_normals": false,
  "bounding_box": null,
  "ink_label": "../paths/20200526152035/textSurface_ink-mask.png",
  "rgb_label": "../paths/20200526152035/textSurface_rgb-mask.png",
  "volcart_texture_label": null
}

=== educelab/ink-id/inkid/examples/DummyTest.volpkg/working/DummyTest_grid1x2_row0_col0.json
{
    "schema_version": "0.1",
    "type": "region",
    "volume": "../volumes/zarr256_20200526145449",
    "ppm": "../paths/20200526152035/textSurface.ppm",
    "mask": "../paths/20200526152035/textSurface_mask.png",
    "invert_normals": false,
    "bounding_box": [
        0,
        0,
        320,
        400
    ],
    "ink_label": "../paths/20200526152035/textSurface_ink-mask.png",
    "rgb_label": "../paths/20200526152035/textSurface_rgb-mask.png",
    "volcart_texture_label": "../paths/20200526152035/textSurface_volcart-texture.png"
}
